name: "Compile Registry Package Sets"
on:
  schedule:
    - cron: '30 19 * * 4'
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: purifix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#all-package-sets -L
      # hopefully this will allow the cachix action to push
      # paths and next run is more likely to complete
      timeout-minutes: 25
